### PR TITLE
fix: support 302 redirect

### LINKED ISSUE #90: Support 302 Found
It seem that 302 Found is not dead.

For example, This rule show error `https://github.com/almin/almin/issues/new is dead. (302 Found)`

- https://github.com/almin/almin/issues/new

### PR DESCRIPTION
**Pull request by azu**
fix #90 

/cc @nodaguti

### CODE REVIEW

File: src/no-dead-link.js [hunk 1]
```diff
@@ -22,6 +22,16 @@ function isRelative(uri) {
 }
 
 /**
+ * Return `true` if the `code` is redirect status code.
+ * @see https://fetch.spec.whatwg.org/#redirect-status
+ * @param {number} code
+ * @returns {boolean}
+ */
+function isRedirect(code) {
+  return code === 301 || code === 302 || code === 303 || code === 307 || code === 308;
```
Comment (azu) [inline src/no-dead-link.js]: Handling 301-303 && 307-308

**Comment by azu** [comment]
@nodaguti How do you think?

**Comment by nodaguti** [comment]
I'm really sorry for being inactive on this package for quite a while.

Thank you for your contribution! 💯
